import os
import subprocess
import numpy as np
def runCustomInput(exec_name, input_template, param_dict, 
    workdir='', label='runCustom',resultfile='eventrate_spectra.dat'):

    """
     Author: Oliver Gorton, 2020

     This is a function for running an executable program with a custom
     input file by replacing keywords in a template used by the executed
     code.

     exec_name: (string) containing the path to and name of the
         executable you want to run
     input_template: (string) this is an input or control file used by the executable
         and which will be edited by this function
     param_dict: (dictionary) of keywords and the values to which those keywords
         will be changed. The keywords are strings which should appear in the 
         input_template file. 
     workdir: (string) name of the working directory where you want to call
         the executable and send the output.
     label: (string) name for this job, to label the input and output files 
         generated by this function.

    """

    path = os.getcwd()
    os.chdir(workdir)

    # File does not exist error trap
    if (not os.path.exists(input_template)):
        print("File %s does not exist."%input_template)
        exit()

    findandreplace = "sed '"
    for keyword in param_dict.keys():
        findandreplace += "s/%s/%s/g;"%(keyword,param_dict[keyword])
    findandreplace += "' %s > %s.input"%(input_template,label)
    returned = subprocess.call(findandreplace, shell=True)

    command = "%s < %s.input > %s.output"%(exec_name,label,label)
    print(command)
    returned = subprocess.call(command,shell=True)
    print("Return code: %s"%returned)

    RecoilE, EventRate = np.loadtxt(resultfile, unpack=True, skiprows=1)

    os.chdir(path)

    return RecoilE, EventRate

