manual:
	pandoc $(DOCS) -o manual.pdf --citeproc

DOCS =\
	  source/intro.md\
	  source/python.md\
	  source/usage.md\
	  source/nuclear.md\
	  source/details.md\
	  source/keywords.md\
	  source/references.md\
	  source/updates.md
